name: Continuous Integration

on:
  push:
    branches: [master]

jobs:
  test:
    name: Unittest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Clean Go module cache before restoring
        run: |
          rm -rf ~/go/pkg/mod
          rm -rf ~/.cache/go-build

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...
